sudo: false
language: ruby
rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0

before_install: gem install bundler -v 1.12.5

script: bundle exec rake record


deploy:
  provider: rubygems
  api_key:
    secure: Gfvy4NhVw0Fr+DVhq4AxvJq5ApdTdyrHd3PcyciUReNp7eRdVv0PecLobwVYIUi3xBJNMWZs8xOIHMMJ2pj+fezNBDsg85HZLO0UcbpwMpllf41SFJFt+JyhQFAkd4Ed2Z4UyFnKrB96+y8eoPcerSKG8KhkibSZkEwTd6wK7Y2Dd90JbozvcIBHujMtB8Uoy5ceABUUynA7aPqVweL8BsS3l8Aq7fWSW9/wDTFgYcyYZb+B96H7zLbH6Zb9RQ5xsXev93aXD9J2sVGKS+Td12P8BmDoT28tD9qe73Fcg7dYYD+gQpLMbPe32AThHBmYPeCLRp6vOcOpmjby2+EItrP8rxJ/imjQbsmhIxham6IBKMeA/J5ytq4b9r10tSiTBewk14icr/Jn6j6dN21R5BSSUI8QZXbo01wD7x5fUwyZBQPbk3DkVeLc5UIxHBZ9a8CQfmMkyeVypXKRStG9nT2JdHm2wESCKgJt9mCpGis/4eVELF0PgcwEWAK/Ktv+VDrTRWGHXAiekVbY2cSFRCvxBScTGz7opMSxmovYm1LqsdFT3FCSK9lnk+oH4OfrQNyr+tCqpQHQeH1LssofLMOeLBp4H1UcbaxDltTs0bDzpXyXx5gXJ5AF1kyoOHuNobrRiyeiLtClFVV65NJqeE0CyUu84dUOv7V55O2D0ak=
  on:
    tags: true


notifications:
  slack:
    secure: YV2pFWnEV9ydw/r4CkUeZ96iyNJ+nqu8LBWLyTplAthjHMfMEOzqutV72pSmso6FGauWRbA4JkYqM45MT1tJ5zV5e0vP7WqqQsNTG3A9vHW6X6KaDp8CLEdznTm1UO2DKWBAJMVoafCfxYEOqFn7QpHbglLajL+R/smyWZSUrcpgvBhPlfo8Btqop0dDGjIm/qYeIyVQy7Hc8Z3sL/RFQPM149jOjPkKSZ8ANlUcDDkQ9MX7A2wBUk3pFsFtgn6k6XWtZAlfEFyC8iDMsGIiJFfhaVssNJYCQ47bzgjNt2Kysd7vU2eTHjoHa6Wk4Xw4TTGjpuL414fiyrB1Ptjt9vF2yl3u8ho2lnjlpCE+UsYl5av5sZfyBM6tMbW1bAf12RCF7iYnoacMz0D5+aE3e6ghFBXCUNbTZBMMPXgTlqAoV/x9v21cvSrnjXWMl4dsy/uUQlUHLiio+2iUwqwFzxeB3wNCK9M94U87ZRHq+MJNph3YxgV9TDaCyHGGOtV10iuTnQRpABI5yddyGR8iRcz53B5i7pGH+0aU8w+tJ3ZxaEv2ofWxhlkgXiGFnbJQ5lbAnoBqjrln5vJl4mEbrkZcj2t2Msx3iuBGaAmRR8ZOHhOeB2JYYrv7ojUnTONPq771uLTSkVSIFBkn/zGossLz4kEBIyG2tWLLgLV5tRk=
