sudo: false
language: ruby
rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0

before_install: gem install bundler -v 1.12.5

script: bundle exec rake record


deploy:
  provider: rubygems
  api_key:
    secure: Gfvy4NhVw0Fr+DVhq4AxvJq5ApdTdyrHd3PcyciUReNp7eRdVv0PecLobwVYIUi3xBJNMWZs8xOIHMMJ2pj+fezNBDsg85HZLO0UcbpwMpllf41SFJFt+JyhQFAkd4Ed2Z4UyFnKrB96+y8eoPcerSKG8KhkibSZkEwTd6wK7Y2Dd90JbozvcIBHujMtB8Uoy5ceABUUynA7aPqVweL8BsS3l8Aq7fWSW9/wDTFgYcyYZb+B96H7zLbH6Zb9RQ5xsXev93aXD9J2sVGKS+Td12P8BmDoT28tD9qe73Fcg7dYYD+gQpLMbPe32AThHBmYPeCLRp6vOcOpmjby2+EItrP8rxJ/imjQbsmhIxham6IBKMeA/J5ytq4b9r10tSiTBewk14icr/Jn6j6dN21R5BSSUI8QZXbo01wD7x5fUwyZBQPbk3DkVeLc5UIxHBZ9a8CQfmMkyeVypXKRStG9nT2JdHm2wESCKgJt9mCpGis/4eVELF0PgcwEWAK/Ktv+VDrTRWGHXAiekVbY2cSFRCvxBScTGz7opMSxmovYm1LqsdFT3FCSK9lnk+oH4OfrQNyr+tCqpQHQeH1LssofLMOeLBp4H1UcbaxDltTs0bDzpXyXx5gXJ5AF1kyoOHuNobrRiyeiLtClFVV65NJqeE0CyUu84dUOv7V55O2D0ak=
  on:
    tags: true


notifications:
  slack:
    secure: WQ1v6XL0he7nxhYUoXMCmQ7mxeSNQsz54z+yVw0LhDDIoWuhPmucV9es/yjTrebe7ZfrM8bmxYLxVVKgphQiXmZx/T76z3zZLNv/BfisLQeT2h1AVxHZ78UK8D3nTrdHM0rvosDv2dq6hC0WxtAZWEP/mGf3Nk+4dBLr4scddYyatApThCD50g1uX/kFs6a44OQ+NrxHFgWgN3NUkUDMMylhtd1mXmy1UDPlElc5h/tAspnrfOh4LwZeKl7lz1CdNDMJURwx8ZdVY22EvwPZISxCa4X6oYpoRoXt2zJ/JJE+H6ICwbo1nXbR6dMHnaZ0EWqgkIQUpGQixAdrsyBt8ddV+lrl6HzyMJcno7aae68oHyipJ5pv8/qQsbLlMlOPWCMeIXZpnzaE/dDLLy/3MZHUa4AWfv0xIHKJN7bhKz8dxfc8bqy/KHvIbbAAWUUBub2F9SRb4LK265skIZmIOLCgqAtKp3THwmhucJhLX4+Gt5ioCx6Cw/HDLD8g4uqR9eUPpRyLVn/ntEzERNPhqWzaHHesIVb3mNfOW3AtLkKfxtdICX4be5AGuhbvKljiFDyf7X582UrbfmfnV1Tjb8elDl8i9/bXFrrv+XtdFuvp2aioIZp81KX9BMVBXiDfugTVLjvwYuGxbxP75cym7jg1uYsMwvKduouQ+N9BRxE=
